export interface Facility {
  id: string;
  name: string;
  type: 'nursery' | 'sick-child' | 'clinic' | 'temporary-care' | 'licensed' | 'kindergarten'; // 幼稚園追加
  address: string;
  lat: number;
  lng: number;
  phone?: string;
  email?: string;
  description?: string;
  rating: number;
  imageUrl: string;
  distance?: number; // in km
  // 地域関連フィールド
  prefecture?: string; // 都道府県（例: '北海道', '富山県'）
  district?: string; // 市区町村（例: '中央区', '富山市', '高岡市'）
  schoolDistrict?: string; // 校区（幼稚園用：例: '月岡', '速星', '水橋中部'）
  websiteUrl?: string; // 施設HP URL
  openingHours?: {
    weekday: string;
    saturday: string;
  };
  capacity?: number; // 一時預かり定員 / 認可保育所定員 / 幼稚園定員
  ageRange?: string; // 対象年齢
  hasLunch?: boolean; // 給食提供
  provider?: string; // 設置者名
  pdfTemplateUrl?: any; // 施設申込書PDFテンプレート（Metro asset）
}

// 札幌市一時保育施設（実データ）
export const sampleFacilities: Facility[] = [
  // 中央区
  {
    id: '1',
    name: '札幌市中央区保育・子育て支援センター',
    type: 'temporary-care',
    address: '札幌市中央区南７条西１３丁目１－１',
    lat: 43.053,
    lng: 141.337,
    phone: '011-511-1155',
    provider: '札幌市',
    description: '札幌市が運営する一時保育施設。産休明けから就学前まで幅広い年齢に対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'central',
    openingHours: {
      weekday: '08:00～18:00',
      saturday: '08:00～18:00',
    },
    capacity: 3,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '2',
    name: '札幌認定こども園',
    type: 'temporary-care',
    address: '札幌市中央区南１条東７丁目２－１５',
    lat: 43.062,
    lng: 141.358,
    phone: '011-251-1555',
    provider: '公益財団法人鉄道弘済会',
    description: '認定こども園での一時預かり。１歳児から対応可能。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'central',
    openingHours: {
      weekday: '08:00～18:00',
      saturday: '08:00～18:00',
    },
    capacity: 9,
    ageRange: '１歳児から就学前まで',
    hasLunch: true,
  },
  {
    id: '3',
    name: 'アスク桑園保育園',
    type: 'temporary-care',
    address: '札幌市中央区北８条西１８丁目３５－１００',
    lat: 43.072,
    lng: 141.326,
    phone: '011-640-5828',
    provider: '株式会社日本保育サービス',
    description: '大規模保育園で定員60名。５か月から預かり可能。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'central',
    openingHours: {
      weekday: '08:00～18:00',
      saturday: '08:00～18:00',
    },
    capacity: 60,
    ageRange: '５か月から就学前まで',
    hasLunch: true,
  },
  // 北区
  {
    id: '4',
    name: '札幌市北区保育・子育て支援センター',
    type: 'temporary-care',
    address: '札幌市北区北２５条西３丁目３－３',
    lat: 43.093,
    lng: 141.346,
    phone: '011-757-5380',
    provider: '札幌市',
    description: '札幌市北区の子育て支援センター。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/3933239/pexels-photo-3933239.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'north',
    openingHours: {
      weekday: '08:00～18:00',
      saturday: '08:00～18:00',
    },
    capacity: 3,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '5',
    name: 'アスク新琴似保育園',
    type: 'temporary-care',
    address: '札幌市北区新琴似７条２丁目２－３５',
    lat: 43.116,
    lng: 141.323,
    phone: '011-769-8680',
    provider: '株式会社日本保育サービス',
    description: '大規模保育園で一時預かり定員60名。土曜日も対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'north',
    openingHours: {
      weekday: '08:00～18:00',
      saturday: '08:00～18:00',
    },
    capacity: 60,
    ageRange: '５か月から就学前まで',
    hasLunch: true,
  },
  {
    id: '6',
    name: '認定こども園メルシー学院',
    type: 'temporary-care',
    address: '札幌市北区屯田５条９丁目１－４６－６',
    lat: 43.145,
    lng: 141.341,
    phone: '011-792-8680',
    provider: '社会福祉法人高陽福祉会',
    description: '大規模認定こども園。一時預かり定員105名で産休明けから対応。',
    rating: 4.8,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'north',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 105,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  // 認可保育所（札幌市認可保育所等一覧より抜粋 - サンプルデータ）
  {
    id: '200',
    name: '認定こども園大谷オアシス保育園',
    type: 'licensed',
    address: '札幌市中央区大通西21丁目',
    lat: 43.063,
    lng: 141.318,
    phone: '011-621-9888',
    provider: '学校法人大谷学園',
    description: '幼保連携型認定こども園。産休明けから受け入れ可能。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'central',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 60,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '201',
    name: '宮の森ライラックこども園',
    type: 'licensed',
    address: '札幌市中央区宮の森3条3丁目',
    lat: 43.073,
    lng: 141.309,
    phone: '011-699-5899',
    provider: '社会福祉法人ノテ福祉会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'central',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '202',
    name: 'あいの里大藤幼稚園',
    type: 'licensed',
    address: '札幌市北区あいの里3条3丁目',
    lat: 43.164,
    lng: 141.429,
    phone: '011-778-2911',
    provider: '学校法人大藤学園',
    description: '幼保連携型認定こども園。生後5か月から受け入れ可能。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'north',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 100,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '203',
    name: '認定こども園メルシー学院',
    type: 'licensed',
    address: '札幌市北区屯田5条9丁目',
    lat: 43.145,
    lng: 141.341,
    phone: '011-792-8680',
    provider: '社会福祉法人高陽福祉会',
    description: '大規模認定こども園。定員105名。',
    rating: 4.8,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'north',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 105,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '204',
    name: '幼保連携型認定こども園もえれ保育園',
    type: 'licensed',
    address: '札幌市東区東雁来11条3丁目',
    lat: 43.144,
    lng: 141.442,
    phone: '011-790-3715',
    provider: '社会福祉法人慧誠会',
    description: '東区の認定こども園。生後5か月から受け入れ可能。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3933239/pexels-photo-3933239.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'east',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 70,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 中央区 追加3件
  {
    id: '205',
    name: '札幌認定こども園',
    type: 'licensed',
    address: '札幌市中央区南1条東7丁目',
    lat: 43.062,
    lng: 141.358,
    phone: '011-251-1555',
    provider: '公益財団法人鉄道弘済会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'central',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '206',
    name: '山鼻保育園',
    type: 'licensed',
    address: '札幌市中央区南12条西8丁目',
    lat: 43.047,
    lng: 141.343,
    phone: '011-511-4612',
    provider: '社会福祉法人山鼻福祉会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'central',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '207',
    name: 'アスク桑園保育園',
    type: 'licensed',
    address: '札幌市中央区北8条西18丁目',
    lat: 43.072,
    lng: 141.326,
    phone: '011-640-5828',
    provider: '株式会社日本保育サービス',
    description: '大規模保育園。5か月から預かり可能。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'central',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 60,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 北区 追加3件
  {
    id: '208',
    name: 'アスク新琴似保育園',
    type: 'licensed',
    address: '札幌市北区新琴似7条2丁目',
    lat: 43.116,
    lng: 141.323,
    phone: '011-769-8680',
    provider: '株式会社日本保育サービス',
    description: '大規模保育園。土曜日も対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'north',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 60,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '209',
    name: '認定こども園屯田すずらん',
    type: 'licensed',
    address: '札幌市北区屯田6条4丁目',
    lat: 43.150,
    lng: 141.339,
    phone: '011-775-8080',
    provider: '学校法人北邦学園',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'north',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 60,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '210',
    name: 'あいの里保育園',
    type: 'licensed',
    address: '札幌市北区あいの里2条2丁目',
    lat: 43.162,
    lng: 141.425,
    phone: '011-778-1088',
    provider: '社会福祉法人ノテ福祉会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'north',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 東区 追加4件
  {
    id: '211',
    name: '幼保連携型認定こども園さつなえのもり',
    type: 'licensed',
    address: '札幌市東区東苗穂8条3丁目',
    lat: 43.103,
    lng: 141.423,
    phone: '011-791-2233',
    provider: '社会福祉法人慧誠会',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'east',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 100,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '212',
    name: '認定こども園札幌愛珠',
    type: 'licensed',
    address: '札幌市東区北38条東9丁目',
    lat: 43.123,
    lng: 141.375,
    phone: '011-750-1123',
    provider: '学校法人リズム学園',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'east',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 80,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '213',
    name: '認定こども園元町杉の子保育園',
    type: 'licensed',
    address: '札幌市東区北14条東16丁目',
    lat: 43.088,
    lng: 141.388,
    phone: '011-781-4477',
    provider: '社会福祉法人杉の子会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'east',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 110,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '214',
    name: 'まことさっぽろこども園',
    type: 'licensed',
    address: '札幌市東区本町2条2丁目',
    lat: 43.097,
    lng: 141.393,
    phone: '011-788-3616',
    provider: '社会福祉法人まこと学園',
    description: '保育所型認定こども園。生後5か月から対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'east',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 白石区 5件
  {
    id: '215',
    name: '双葉こども園',
    type: 'licensed',
    address: '札幌市白石区栄通15丁目',
    lat: 43.040,
    lng: 141.441,
    phone: '011-851-7463',
    provider: '社会福祉法人双葉福祉会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'white-stone',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 130,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '216',
    name: '認定こども園菊水すずらん',
    type: 'licensed',
    address: '札幌市白石区菊水1条3丁目',
    lat: 43.052,
    lng: 141.380,
    phone: '011-811-5714',
    provider: '社会福祉法人菊水福祉会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'white-stone',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '217',
    name: '認定こども園ピッコリーノ学院',
    type: 'licensed',
    address: '札幌市白石区北郷1条6丁目',
    lat: 43.071,
    lng: 141.413,
    phone: '011-376-1181',
    provider: '学校法人静修学園',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'white-stone',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 160,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '218',
    name: '白石中央保育園',
    type: 'licensed',
    address: '札幌市白石区中央3条5丁目',
    lat: 43.054,
    lng: 141.402,
    phone: '011-861-5178',
    provider: '社会福祉法人北海道社会事業協会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'white-stone',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 120,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '219',
    name: '北白石こども園',
    type: 'licensed',
    address: '札幌市白石区北郷2条3丁目',
    lat: 43.070,
    lng: 141.406,
    phone: '011-874-8222',
    provider: '社会福祉法人北白石福祉会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'white-stone',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 厚別区 5件
  {
    id: '220',
    name: '認定こども園いちい幼稚園・保育園',
    type: 'licensed',
    address: '札幌市厚別区もみじ台西5丁目',
    lat: 43.029,
    lng: 141.493,
    phone: '011-897-1311',
    provider: '社会福祉法人いちい福祉会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'atsubetsu',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 125,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '221',
    name: '認定こども園桜台いちい幼稚園・保育園',
    type: 'licensed',
    address: '札幌市厚別区厚別西611',
    lat: 43.030,
    lng: 141.477,
    phone: '011-895-3331',
    provider: '社会福祉法人いちい福祉会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'atsubetsu',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 49,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '222',
    name: '認定こども園厚別さくら木保育園',
    type: 'licensed',
    address: '札幌市厚別区厚別東3条1丁目',
    lat: 43.032,
    lng: 141.495,
    phone: '011-898-6200',
    provider: '社会福祉法人桜陽福祉会',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.8,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'atsubetsu',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 70,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '223',
    name: '認定こども園新さっぽろ幼稚園・保育園',
    type: 'licensed',
    address: '札幌市厚別区上野幌1条2丁目',
    lat: 43.021,
    lng: 141.481,
    phone: '011-890-7171',
    provider: '学校法人リズム学園',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'atsubetsu',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '224',
    name: '厚別西認定こども園',
    type: 'licensed',
    address: '札幌市厚別区厚別西4条2丁目',
    lat: 43.029,
    lng: 141.469,
    phone: '011-802-3115',
    provider: '社会福祉法人北海道社会事業協会',
    description: '保育所型認定こども園。生後5か月から対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'atsubetsu',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 豊平区 5件
  {
    id: '225',
    name: '認定こども園月寒そらいろ保育園',
    type: 'licensed',
    address: '札幌市豊平区月寒西4条6丁目',
    lat: 43.009,
    lng: 141.378,
    phone: '011-595-8312',
    provider: '社会福祉法人北翔会',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'toyohira',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '226',
    name: '東月寒にれこども園',
    type: 'licensed',
    address: '札幌市豊平区月寒東3条16丁目',
    lat: 43.009,
    lng: 141.421,
    phone: '011-853-6644',
    provider: '社会福祉法人にれ福祉会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'toyohira',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 120,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '227',
    name: '認定こども園札幌ゆたか幼稚園',
    type: 'licensed',
    address: '札幌市豊平区豊平4条3丁目',
    lat: 43.038,
    lng: 141.379,
    phone: '011-822-8686',
    provider: '学校法人豊平学園',
    description: '幼保連携型認定こども園。1歳児から対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'toyohira',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '1歳児から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '228',
    name: '平岸興正こども園',
    type: 'licensed',
    address: '札幌市豊平区平岸1条11丁目',
    lat: 43.034,
    lng: 141.392,
    phone: '011-824-2100',
    provider: '社会福祉法人北海道興正学園',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'toyohira',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '229',
    name: '中の島興正こども園',
    type: 'licensed',
    address: '札幌市豊平区中の島2条1丁目',
    lat: 43.011,
    lng: 141.371,
    phone: '011-831-1600',
    provider: '社会福祉法人北海道興正学園',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'toyohira',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 120,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 清田区 5件
  {
    id: '230',
    name: '札幌市立認定こども園にじいろ',
    type: 'licensed',
    address: '札幌市清田区真栄2条1丁目',
    lat: 42.989,
    lng: 141.473,
    phone: '011-883-3345',
    provider: '札幌市',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.8,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'kiyota',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '231',
    name: '幼保連携型認定こども園きよた幼稚園',
    type: 'licensed',
    address: '札幌市清田区清田1条2丁目',
    lat: 42.998,
    lng: 141.471,
    phone: '011-881-2453',
    provider: '学校法人清田学園',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'kiyota',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 70,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '232',
    name: '認定こども園まつばの杜',
    type: 'licensed',
    address: '札幌市清田区新発寒5条9丁目',
    lat: 43.016,
    lng: 141.446,
    phone: '011-683-8931',
    provider: '社会福祉法人晴雅会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'kiyota',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 110,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '233',
    name: '認定こども園からまつ保育園',
    type: 'licensed',
    address: '札幌市清田区里塚2条2丁目',
    lat: 42.993,
    lng: 141.477,
    phone: '011-889-3000',
    provider: '社会福祉法人幌北学園',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'kiyota',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 140,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '234',
    name: '花山認定こども園',
    type: 'licensed',
    address: '札幌市清田区里塚緑ヶ丘3丁目',
    lat: 42.988,
    lng: 141.483,
    phone: '011-886-0415',
    provider: '社会福祉法人花山福祉会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'kiyota',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 100,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 南区 5件
  {
    id: '235',
    name: 'ときわみなみのこどもえん',
    type: 'licensed',
    address: '札幌市南区真駒内380',
    lat: 42.984,
    lng: 141.349,
    phone: '011-591-0123',
    provider: '社会福祉法人ノテ福祉会',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'south',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 60,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '236',
    name: '真駒内聖母認定こども園',
    type: 'licensed',
    address: '札幌市南区真駒内上町4丁目',
    lat: 42.988,
    lng: 141.352,
    phone: '011-581-0745',
    provider: '学校法人聖母学院',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'south',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '237',
    name: '真駒内保育園',
    type: 'licensed',
    address: '札幌市南区真駒内南町1丁目',
    lat: 42.981,
    lng: 141.348,
    phone: '011-581-0005',
    provider: '社会福祉法人北海道社会事業協会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.8,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'south',
    openingHours: {
      weekday: '07:00～20:00',
      saturday: '07:00～20:00',
    },
    capacity: 120,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '238',
    name: '認定こども園澄川保育園',
    type: 'licensed',
    address: '札幌市南区澄川5条5丁目',
    lat: 43.006,
    lng: 141.358,
    phone: '011-821-0471',
    provider: '社会福祉法人澄川保育園',
    description: '保育所型認定こども園。生後5か月から対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'south',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '239',
    name: 'くまの子保育園',
    type: 'licensed',
    address: '札幌市南区南沢2条3丁目',
    lat: 42.989,
    lng: 141.318,
    phone: '011-578-5133',
    provider: '社会福祉法人熊の子福祉会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'south',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 60,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 西区 5件
  {
    id: '240',
    name: '認定こども園宮の沢すずらん',
    type: 'licensed',
    address: '札幌市西区宮の沢1条2丁目',
    lat: 43.089,
    lng: 141.261,
    phone: '011-662-8181',
    provider: '社会福祉法人宮の沢福祉会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'west',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '241',
    name: '認定こども園西野そらいろ保育園',
    type: 'licensed',
    address: '札幌市西区西野4条7丁目',
    lat: 43.075,
    lng: 141.235,
    phone: '011-667-3345',
    provider: '社会福祉法人北翔会',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'west',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '242',
    name: '認定こども園にしの',
    type: 'licensed',
    address: '札幌市西区西野9条5丁目',
    lat: 43.072,
    lng: 141.223,
    phone: '011-668-8881',
    provider: '社会福祉法人西野福祉会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.8,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'west',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '243',
    name: '発寒保育園',
    type: 'licensed',
    address: '札幌市西区発寒3条1丁目',
    lat: 43.086,
    lng: 141.279,
    phone: '011-661-3997',
    provider: '社会福祉法人発寒福祉会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'west',
    openingHours: {
      weekday: '07:00～20:00',
      saturday: '07:00～20:00',
    },
    capacity: 120,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '244',
    name: '二十四軒保育園',
    type: 'licensed',
    address: '札幌市西区二十四軒3条7丁目',
    lat: 43.079,
    lng: 141.304,
    phone: '011-643-9030',
    provider: '社会福祉法人明日葉会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'west',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 130,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  // 手稲区 5件
  {
    id: '245',
    name: '手稲やまなみ子ども園',
    type: 'licensed',
    address: '札幌市手稲区稲穂2条5丁目',
    lat: 43.124,
    lng: 141.244,
    phone: '011-695-8073',
    provider: '社会福祉法人北海道社会事業協会',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.8,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'teine',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 125,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '246',
    name: 'ていねあすなろ認定こども園',
    type: 'licensed',
    address: '札幌市手稲区曙5条3丁目',
    lat: 43.138,
    lng: 141.241,
    phone: '011-691-2346',
    provider: '社会福祉法人手稲福祉会',
    description: '幼保連携型認定こども園。産休明けから対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'teine',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 70,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '247',
    name: '星置ピノキオ認定こども園',
    type: 'licensed',
    address: '札幌市手稲区星置1条1丁目',
    lat: 43.155,
    lng: 141.224,
    phone: '011-686-8377',
    provider: '学校法人新琴似中央学園',
    description: '幼保連携型認定こども園。生後5か月から対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'teine',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 100,
    ageRange: '生後５か月から就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '248',
    name: '稲穂中央保育園',
    type: 'licensed',
    address: '札幌市手稲区稲穂4条7丁目',
    lat: 43.123,
    lng: 141.250,
    phone: '011-522-8300',
    provider: '社会福祉法人北海道社会事業協会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'teine',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },
  {
    id: '249',
    name: '前田中央保育園',
    type: 'licensed',
    address: '札幌市手稲区前田8条12丁目',
    lat: 43.163,
    lng: 141.220,
    phone: '011-681-0010',
    provider: '社会福祉法人前田福祉会',
    description: '保育所型認定こども園。産休明けから対応。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '北海道',
    district: 'teine',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 120,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
    pdfTemplateUrl: require('../docs/facilities/sapporoninkahoiku/251001ninnkahoikusyoitirann.pdf'),
  },

  // ============ 富山県の保育施設 ============
  // 富山市
  {
    id: '300',
    name: '富山市中央保育所',
    type: 'licensed',
    address: '富山県富山市新富町1丁目2-3',
    lat: 36.695,
    lng: 137.213,
    phone: '076-421-5430',
    provider: '富山市',
    description: '富山市が運営する認可保育所。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-中央',
    openingHours: {
      weekday: '07:30～18:30',
      saturday: '07:30～18:30',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '301',
    name: '認定こども園富山いずみ',
    type: 'licensed',
    address: '富山県富山市泉町1-5-10',
    lat: 36.698,
    lng: 137.208,
    phone: '076-425-2222',
    provider: '社会福祉法人富山いずみ福祉会',
    description: '幼保連携型認定こども園。生後6か月から受け入れ可能。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-中央',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 120,
    ageRange: '生後６か月から就学前まで',
    hasLunch: true,
  },
  {
    id: '302',
    name: '富山大学附属幼稚園',
    type: 'licensed',
    address: '富山県富山市五福3190',
    lat: 36.698,
    lng: 137.185,
    phone: '076-445-2802',
    provider: '国立大学法人富山大学',
    description: '国立大学附属の認定こども園。3歳児から対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-西部',
    openingHours: {
      weekday: '08:00～17:00',
      saturday: '未実施',
    },
    capacity: 60,
    ageRange: '3歳児から就学前まで',
    hasLunch: true,
  },
  {
    id: '303',
    name: '婦中ひまわり保育園',
    type: 'licensed',
    address: '富山県富山市婦中町速星450',
    lat: 36.642,
    lng: 137.173,
    phone: '076-466-3030',
    provider: '社会福祉法人ひまわり福祉会',
    description: '婦中地域の保育園。産休明けから対応。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-婦中',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 80,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '304',
    name: '八尾さくら保育園',
    type: 'licensed',
    address: '富山県富山市八尾町井田126',
    lat: 36.606,
    lng: 137.197,
    phone: '076-454-5050',
    provider: '社会福祉法人八尾福祉会',
    description: '八尾地域の認可保育園。自然豊かな環境で保育。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-八尾',
    openingHours: {
      weekday: '07:30～18:30',
      saturday: '07:30～18:30',
    },
    capacity: 60,
    ageRange: '生後６か月から就学前まで',
    hasLunch: true,
  },

  // 高岡市
  {
    id: '305',
    name: '高岡市中央保育園',
    type: 'licensed',
    address: '富山県高岡市木津1090',
    lat: 36.745,
    lng: 137.024,
    phone: '0766-25-1122',
    provider: '高岡市',
    description: '高岡市が運営する認可保育園。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'takaoka',
    openingHours: {
      weekday: '07:30～18:30',
      saturday: '07:30～18:30',
    },
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '306',
    name: '認定こども園高岡みどり',
    type: 'licensed',
    address: '富山県高岡市緑町5-1',
    lat: 36.751,
    lng: 137.019,
    phone: '0766-22-3333',
    provider: '社会福祉法人高岡緑福祉会',
    description: '幼保連携型認定こども園。生後6か月から対応。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'takaoka',
    openingHours: {
      weekday: '07:00～19:00',
      saturday: '07:00～19:00',
    },
    capacity: 150,
    ageRange: '生後６か月から就学前まで',
    hasLunch: true,
  },

  // 射水市
  {
    id: '307',
    name: '射水市あおぞら保育園',
    type: 'licensed',
    address: '富山県射水市小島1200',
    lat: 36.732,
    lng: 137.088,
    phone: '0766-52-4400',
    provider: '射水市',
    description: '射水市の公立保育園。産休明けから対応。',
    rating: 4.4,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'imizu',
    openingHours: {
      weekday: '07:30～18:30',
      saturday: '07:30～18:30',
    },
    capacity: 70,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },

  // 砺波市
  {
    id: '308',
    name: '砺波市チューリップ保育園',
    type: 'licensed',
    address: '富山県砺波市栄町7-3',
    lat: 36.643,
    lng: 136.964,
    phone: '0763-33-2200',
    provider: '砺波市',
    description: 'チューリップの町、砺波市の保育園。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'tonami',
    openingHours: {
      weekday: '07:30～18:30',
      saturday: '07:30～12:30',
    },
    capacity: 80,
    ageRange: '生後６か月から就学前まで',
    hasLunch: true,
  },

  // 魚津市
  {
    id: '309',
    name: '魚津市うおづっ子保育園',
    type: 'licensed',
    address: '富山県魚津市釈迦堂1-10-15',
    lat: 36.826,
    lng: 137.408,
    phone: '0765-22-5500',
    provider: '魚津市',
    description: '魚津市の公立保育園。海の近くで自然体験も豊富。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'uozu',
    openingHours: {
      weekday: '07:30～18:30',
      saturday: '07:30～18:30',
    },
    capacity: 90,
    ageRange: '生後６か月から就学前まで',
    hasLunch: true,
  },

  // ============ 富山市の幼稚園（富山市オープンデータより）============
  {
    id: '310',
    name: '富山市立月岡幼稚園',
    type: 'kindergarten',
    address: '富山県富山市上千俵町508',
    lat: 36.622,
    lng: 137.253,
    phone: '076-429-4959',
    provider: '富山市',
    description: '月岡校区の市立幼稚園。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-南部',
    schoolDistrict: '月岡',
    websiteUrl: 'https://swa.city.toyama.toyama.jp/swas/index.php?frame=webindex&page=ePage&enc=ca03eba42a20feab',
    capacity: 105,
    ageRange: '3歳児から就学前まで',
    hasLunch: true,
  },
  {
    id: '311',
    name: '富山市立速星幼稚園',
    type: 'kindergarten',
    address: '富山県富山市婦中町速星706-1',
    lat: 36.659,
    lng: 137.156,
    phone: '076-465-2183',
    provider: '富山市',
    description: '速星校区の市立幼稚園。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-婦中',
    schoolDistrict: '速星',
    websiteUrl: 'https://swa.city.toyama.toyama.jp/swas/index.php?frame=webindex&page=ePage&enc=9d0a30e0e2e3d2ce',
    capacity: 95,
    ageRange: '3歳児から就学前まで',
    hasLunch: true,
  },
  {
    id: '312',
    name: '富山市立水橋幼稚園',
    type: 'kindergarten',
    address: '富山県富山市水橋舘町390-13',
    lat: 36.77,
    lng: 137.35,
    phone: '076-478-0568',
    provider: '富山市',
    description: '水橋中部校区の市立幼稚園。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-水橋',
    schoolDistrict: '水橋中部',
    websiteUrl: 'https://swa.city.toyama.toyama.jp/swas/index.php?frame=webindex&page=ePage&enc=0e0b50e9f3e1d4d0',
    capacity: 105,
    ageRange: '3歳児から就学前まで',
    hasLunch: true,
  },
  {
    id: '313',
    name: '富山大学教育学部附属幼稚園',
    type: 'kindergarten',
    address: '富山県富山市五艘1300',
    lat: 36.708,
    lng: 137.197,
    phone: '076-445-2812',
    provider: '国立大学法人富山大学',
    description: '桜谷校区の国立大学附属幼稚園。',
    rating: 4.7,
    imageUrl: 'https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-中央',
    schoolDistrict: '桜谷',
    websiteUrl: 'https://www.fuzoku.u-toyama.ac.jp/fuzoku/fuzoku-yotien/',
    capacity: 160,
    ageRange: '3歳児から就学前まで',
    hasLunch: true,
  },
  {
    id: '314',
    name: 'あさひ幼稚園',
    type: 'kindergarten',
    address: '富山県富山市東石金町8-28',
    lat: 36.69,
    lng: 137.22,
    phone: '076-425-1184',
    provider: '学校法人あさひ学園',
    description: '東部校区の私立幼稚園。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-東部',
    schoolDistrict: '東部',
    capacity: 25,
    ageRange: '3歳児から就学前まで',
    hasLunch: true,
  },
  {
    id: '315',
    name: '愛護幼稚園',
    type: 'kindergarten',
    address: '富山県富山市山王町4-49',
    lat: 36.687,
    lng: 137.213,
    phone: '076-423-4342',
    provider: '学校法人愛護学園',
    description: '中央校区の私立幼稚園。キリスト教保育を実践。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-中央',
    schoolDistrict: '中央',
    websiteUrl: 'https://aigo-youchien.org/',
    capacity: 15,
    ageRange: '3歳児から就学前まで',
    hasLunch: true,
  },
  {
    id: '316',
    name: '五番町幼稚園',
    type: 'kindergarten',
    address: '富山県富山市古鍛冶町2-22',
    lat: 36.688,
    lng: 137.218,
    phone: '076-421-8759',
    provider: '学校法人五番町学園',
    description: '中央校区の私立幼稚園。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-中央',
    schoolDistrict: '中央',
    capacity: 60,
    ageRange: '3歳児から就学前まで',
    hasLunch: true,
  },
  {
    id: '317',
    name: '富山カワイ幼稚園',
    type: 'kindergarten',
    address: '富山県富山市向新庄町五丁目5-6',
    lat: 36.705,
    lng: 137.265,
    phone: '076-451-5884',
    provider: '学校法人富山新庄学園',
    description: '新庄北校区の私立幼稚園。',
    rating: 4.6,
    imageUrl: 'https://images.pexels.com/photos/3038285/pexels-photo-3038285.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-東部',
    schoolDistrict: '新庄北',
    websiteUrl: 'https://toyamakawai.ed.jp/',
    capacity: 150,
    ageRange: '3歳児から就学前まで',
    hasLunch: true,
  },

  // ============ 富山市の公立保育所（富山市オープンデータより）============
  {
    id: '318',
    name: '雲雀ケ丘保育所',
    type: 'licensed',
    address: '富山県富山市鹿島町一丁目3-16',
    lat: 36.695,
    lng: 137.213,
    phone: '076-424-0472',
    provider: '富山市',
    description: '中央地区の保育施設。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-中央',
    schoolDistrict: '芝園',
    capacity: 100,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '319',
    name: '清水保育所',
    type: 'licensed',
    address: '富山県富山市旭町10-17',
    lat: 36.695,
    lng: 137.213,
    phone: '076-423-1630',
    provider: '富山市',
    description: '中央地区の保育施設。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-中央',
    schoolDistrict: '中央',
    capacity: 95,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '320',
    name: '柳町保育所',
    type: 'licensed',
    address: '富山県富山市於保多町1-23',
    lat: 36.695,
    lng: 137.213,
    phone: '076-432-7051',
    provider: '富山市',
    description: '中央地区の保育施設。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-中央',
    schoolDistrict: '柳町',
    capacity: 110,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '321',
    name: '稲荷元町保育所',
    type: 'licensed',
    address: '富山県富山市稲荷元町二丁目13-13',
    lat: 36.695,
    lng: 137.213,
    phone: '076-441-6719',
    provider: '富山市',
    description: '中央地区の保育施設。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-中央',
    schoolDistrict: '柳町',
    capacity: 105,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '322',
    name: '岩瀬保育所',
    type: 'licensed',
    address: '富山県富山市岩瀬御蔵町1',
    lat: 36.695,
    lng: 137.213,
    phone: '076-437-9675',
    provider: '富山市',
    description: '北部地区の保育施設。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-北部',
    schoolDistrict: '岩瀬',
    capacity: 90,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '323',
    name: '浜黒崎保育所',
    type: 'licensed',
    address: '富山県富山市古志町三丁目1-3',
    lat: 36.695,
    lng: 137.213,
    phone: '076-437-9845',
    provider: '富山市',
    description: '北部地区の保育施設。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-北部',
    schoolDistrict: '大広田',
    capacity: 70,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '324',
    name: '双葉保育所',
    type: 'licensed',
    address: '富山県富山市草島256-1',
    lat: 36.695,
    lng: 137.213,
    phone: '076-435-0222',
    provider: '富山市',
    description: '和合地区の保育施設。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-和合',
    schoolDistrict: '草島',
    capacity: 55,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '325',
    name: '和合保育所',
    type: 'licensed',
    address: '富山県富山市布目4173',
    lat: 36.695,
    lng: 137.213,
    phone: '076-435-0386',
    provider: '富山市',
    description: '和合地区の保育施設。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-和合',
    schoolDistrict: '倉垣',
    capacity: 55,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '326',
    name: '呉羽保育所',
    type: 'licensed',
    address: '富山県富山市呉羽町2247-18',
    lat: 36.695,
    lng: 137.213,
    phone: '076-434-2446',
    provider: '富山市',
    description: '呉羽地区の保育施設。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-呉羽',
    schoolDistrict: '呉羽',
    capacity: 175,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
  {
    id: '327',
    name: '長岡保育所',
    type: 'licensed',
    address: '富山県富山市呉羽町４９９０',
    lat: 36.695,
    lng: 137.213,
    phone: '076-432-2593',
    provider: '富山市',
    description: '呉羽地区の保育施設。旧呉羽保育所から移転。',
    rating: 4.5,
    imageUrl: 'https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600',
    prefecture: '富山県',
    district: 'toyama-呉羽',
    schoolDistrict: '長岡',
    capacity: 65,
    ageRange: '産休明けから就学前まで',
    hasLunch: true,
  },
];

// フィルタリング関数
export const filterFacilities = (
  facilities: Facility[],
  filters: {
    types: string[];
    prefectures: string[];
    districts: string[];
    hasSaturday: boolean | null;
    capacityRange: string | null;
  }
): Facility[] => {
  return facilities.filter(facility => {
    // 施設タイプフィルター
    if (filters.types.length > 0 && !filters.types.includes(facility.type)) {
      return false;
    }

    // 都道府県フィルター
    if (filters.prefectures.length > 0) {
      if (!facility.prefecture) return false;

      // 都道府県IDとマッチングするために、prefectureフィールドを使用
      // facility.prefecture は '北海道' or '富山県' などの文字列
      // filters.prefectures は ['hokkaido', 'toyama'] などのIDの配列
      const prefectureMatches = filters.prefectures.some(prefId => {
        if (prefId === 'hokkaido' && facility.prefecture === '北海道') return true;
        if (prefId === 'toyama' && facility.prefecture === '富山県') return true;
        return false;
      });

      if (!prefectureMatches) return false;
    }

    // 市区町村フィルター
    if (filters.districts.length > 0 && facility.district && !filters.districts.includes(facility.district)) {
      return false;
    }

    // 土曜日対応フィルター
    if (filters.hasSaturday === true && facility.openingHours?.saturday === '未実施') {
      return false;
    }

    // 定員規模フィルター
    if (filters.capacityRange && facility.capacity) {
      if (filters.capacityRange === 'small' && facility.capacity > 10) {
        return false;
      }
      if (filters.capacityRange === 'medium' && (facility.capacity <= 10 || facility.capacity > 30)) {
        return false;
      }
      if (filters.capacityRange === 'large' && facility.capacity <= 30) {
        return false;
      }
    }

    return true;
  });
};