/**
 * 富山市保育施設データ（自動生成）
 * 生成日時: 2025/12/2 7:04:09
 * 元データ: 富山市オープンデータ
 */

import { Facility } from './facilities';

export const toyamaFacilities: Facility[] = [
  {
    "id": "318",
    "name": "雲雀ケ丘保育所",
    "type": "licensed",
    "address": "富山県富山市鹿島町一丁目3-16",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-424-0472",
    "provider": "富山市",
    "description": "中央地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-中央",
    "schoolDistrict": "芝園",
    "capacity": 100,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  },
  {
    "id": "319",
    "name": "清水保育所",
    "type": "licensed",
    "address": "富山県富山市旭町10-17",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-423-1630",
    "provider": "富山市",
    "description": "中央地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-中央",
    "schoolDistrict": "中央",
    "capacity": 95,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  },
  {
    "id": "320",
    "name": "柳町保育所",
    "type": "licensed",
    "address": "富山県富山市於保多町1-23",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-432-7051",
    "provider": "富山市",
    "description": "中央地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-中央",
    "schoolDistrict": "柳町",
    "capacity": 110,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  },
  {
    "id": "321",
    "name": "稲荷元町保育所",
    "type": "licensed",
    "address": "富山県富山市稲荷元町二丁目13-13",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-441-6719",
    "provider": "富山市",
    "description": "中央地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-中央",
    "schoolDistrict": "柳町",
    "capacity": 105,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  },
  {
    "id": "322",
    "name": "岩瀬保育所",
    "type": "licensed",
    "address": "富山県富山市岩瀬御蔵町1",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-437-9675",
    "provider": "富山市",
    "description": "北部地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-北部",
    "schoolDistrict": "岩瀬",
    "capacity": 90,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  },
  {
    "id": "323",
    "name": "浜黒崎保育所",
    "type": "licensed",
    "address": "富山県富山市古志町三丁目1-3",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-437-9845",
    "provider": "富山市",
    "description": "北部地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-北部",
    "schoolDistrict": "大広田",
    "capacity": 70,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  },
  {
    "id": "324",
    "name": "双葉保育所",
    "type": "licensed",
    "address": "富山県富山市草島256-1",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-435-0222",
    "provider": "富山市",
    "description": "和合地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-和合",
    "schoolDistrict": "草島",
    "capacity": 55,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  },
  {
    "id": "325",
    "name": "和合保育所",
    "type": "licensed",
    "address": "富山県富山市布目4173",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-435-0386",
    "provider": "富山市",
    "description": "和合地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-和合",
    "schoolDistrict": "倉垣",
    "capacity": 55,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  },
  {
    "id": "326",
    "name": "呉羽保育所",
    "type": "licensed",
    "address": "富山県富山市呉羽町2247-18",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-434-2446",
    "provider": "富山市",
    "description": "呉羽地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-呉羽",
    "schoolDistrict": "呉羽",
    "capacity": 175,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  },
  {
    "id": "327",
    "name": "長岡保育所（※3）",
    "type": "licensed",
    "address": "富山県富山市呉羽町４９９０\n（旧呉羽保育所）",
    "lat": 36.695,
    "lng": 137.213,
    "phone": "076-432-2593",
    "provider": "富山市",
    "description": "呉羽地区の保育施設。",
    "rating": 4.5,
    "imageUrl": "https://images.pexels.com/photos/1001914/pexels-photo-1001914.jpeg?auto=compress&cs=tinysrgb&w=600",
    "prefecture": "富山県",
    "district": "toyama-呉羽",
    "schoolDistrict": "長岡",
    "capacity": 65,
    "ageRange": "産休明けから就学前まで",
    "hasLunch": true
  }
];
